from fastapi import APIRouter
from app.core.database import supabase
from app.utils.token_counter import count_tokens
import json

router = APIRouter(prefix="/projects/{project_id}/context", tags=["Context"])

def get_memory(project_id: str):
    res = supabase.table("project_memory")\
        .select("*")\
        .eq("project_id", project_id)\
        .execute()
    return res.data[0] if res.data else {"memory_data": {}, "version": 1}

def to_markdown(memory_data: dict, project_name: str, version: int) -> str:
    lines = [
        f"# {project_name} — Project Memory",
        f"_ContextBridge Export • Memory Version {version}_\n",
        "> This file was generated by ContextBridge.",
        "> Paste it at the start of your AI coding agent session to restore project context.\n",
        "---\n"
    ]
    sections = [
        ("project_overview", "## Project Overview", "text"),
        ("requirements", "## Requirements", "list"),
        ("architecture", "## Architecture", "text"),
        ("technologies", "## Technologies", "list"),
        ("current_progress", "## Current Progress", "list"),
        ("key_decisions", "## Key Decisions", "list"),
        ("pending_tasks", "## Pending Tasks", "list"),
        ("known_issues", "## Known Issues", "list"),
        ("agent_instructions", "## Agent Instructions", "list"),
    ]
    for key, header, kind in sections:
        value = memory_data.get(key)
        if not value:
            continue
        lines.append(header)
        if kind == "list":
            for item in value:
                lines.append(f"- {item}")
        else:
            lines.append(str(value))
        lines.append("")
    return "\n".join(lines)

@router.get("/export/markdown")
def export_markdown(project_id: str):
    proj = supabase.table("projects").select("*").eq("id", project_id).execute()
    name = proj.data[0]["name"] if proj.data else "Project"
    record = get_memory(project_id)
    original = json.dumps(record["memory_data"], indent=2)
    md = to_markdown(record["memory_data"], name, record["version"])
    return {
        "markdown": md,
        "original_tokens": count_tokens(original),
        "compressed_tokens": count_tokens(md),
    }

@router.get("/export/json")
def export_json(project_id: str):
    proj = supabase.table("projects").select("*").eq("id", project_id).execute()
    project = proj.data[0] if proj.data else {}
    record = get_memory(project_id)
    return {
        "memory_data": record["memory_data"],
        "version": record["version"],
        "project_name": project.get("name", ""),
        "exported_at": __import__("datetime").datetime.utcnow().isoformat()
    }

AGENT_INSTRUCTIONS_MD = """# ContextBridge — Agent Instructions

## How to Use This Context

This folder was exported by ContextBridge. It contains structured project memory
for an AI coding agent to continue development without losing context.

## Files in This Package

- `project-memory.md` — Human and agent readable project memory. Paste this at
  the start of your coding agent session.
- `project-memory.json` — Structured memory for programmatic use.
- `project-config.json` — Project metadata and export information.
- `AGENT-INSTRUCTIONS.md` — This file.

## Instructions for the AI Coding Agent

1. Read `project-memory.md` completely before making any changes.
2. Check Current Progress to understand what is already done.
3. Check Pending Tasks to understand what needs to be done next.
4. Check Known Issues before starting work.
5. Follow all Agent Instructions listed in the memory file.
6. Respect all Key Decisions — do not reverse them without good reason.
7. Preserve the existing project structure unless instructed otherwise.
8. After completing significant work, ask the user to update ContextBridge memory.

## Workflow

Agent Session Ends
    ↓
User imports session into ContextBridge
    ↓
ContextBridge extracts context
    ↓
User approves memory updates
    ↓
New export generated
    ↓
Next agent session starts with fresh context

## Important

- This file was generated automatically. Do not edit it manually.
- Always use the latest export from ContextBridge for the most current context.
- If context seems outdated, ask the user to export a fresh copy.
"""

@router.get("/export/package")
def export_package(project_id: str):
    proj = supabase.table("projects").select("*").eq("id", project_id).execute()
    project = proj.data[0] if proj.data else {}
    record = get_memory(project_id)
    name = project.get("name", "Project")
    version = record["version"]

    md = to_markdown(record["memory_data"], name, version)
    config = {
        "project_id": project_id,
        "project_name": name,
        "memory_format": "contextbridge-v1",
        "export_version": version
    }
    return {
        "project_memory_md": md,
        "project_memory_json": record["memory_data"],
        "project_config_json": config,
        "agent_instructions_md": AGENT_INSTRUCTIONS_MD
    }