from fastapi import APIRouter, HTTPException
from app.core.database import supabase
from app.utils.token_counter import count_tokens
import json

router = APIRouter(prefix="/projects/{project_id}/handoff", tags=["Agent Handoff"])


def get_project(project_id: str) -> dict:
    res = supabase.table("projects").select("*").eq("id", project_id).execute()
    if not res.data:
        raise HTTPException(status_code=404, detail="Project not found")
    return res.data[0]


def get_memory(project_id: str) -> dict:
    res = supabase.table("project_memory").select("*").eq("project_id", project_id).execute()
    if res.data:
        return res.data[0]
    return {"memory_data": {}, "version": 1}


def build_full_prompt(project: dict, memory: dict, version: int) -> str:
    m = memory
    lines = [
        f"# ContextBridge Agent Handoff",
        f"## Project: {project['name']}",
        f"_Memory Version: {version}_",
        "",
        "> You are continuing work on an existing software project.",
        "> Read all sections carefully before making any changes.",
        "> Follow the Agent Instructions at the bottom of this document.",
        "",
        "---",
        "",
    ]

    if m.get("project_overview"):
        lines += ["## Project Overview", m["project_overview"], ""]

    if m.get("architecture"):
        lines += ["## Architecture", m["architecture"], ""]

    if m.get("technologies"):
        lines += ["## Technologies Used"]
        for t in m["technologies"]:
            lines.append(f"- {t}")
        lines.append("")

    if m.get("current_progress"):
        lines += ["## Current Progress (Already Done)"]
        for t in m["current_progress"]:
            lines.append(f"- ✅ {t}")
        lines.append("")

    if m.get("key_decisions"):
        lines += ["## Key Decisions (Do Not Reverse These)"]
        for d in m["key_decisions"]:
            lines.append(f"- {d}")
        lines.append("")

    if m.get("known_issues"):
        lines += ["## Known Issues & Blockers"]
        for i in m["known_issues"]:
            lines.append(f"- ⚠️ {i}")
        lines.append("")

    if m.get("pending_tasks"):
        lines += ["## Pending Tasks (Your Work)"]
        for t in m["pending_tasks"]:
            lines.append(f"- [ ] {t}")
        lines.append("")

    if m.get("requirements"):
        lines += ["## Requirements"]
        for r in m["requirements"]:
            lines.append(f"- {r}")
        lines.append("")

    if m.get("agent_instructions"):
        lines += ["## Agent Instructions (Follow These)"]
        for i in m["agent_instructions"]:
            lines.append(f"- {i}")
        lines.append("")

    lines += [
        "---",
        "_Context generated by ContextBridge. Update project memory after significant changes._"
    ]

    return "\n".join(lines)


def build_task_prompt(project: dict, memory: dict, version: int, task: str) -> str:
    m = memory
    lines = [
        f"# ContextBridge — Task-Focused Context",
        f"## Project: {project['name']}",
        f"_Memory Version: {version}_",
        "",
        f"## Your Task",
        f"> {task}",
        "",
        "---",
        "",
    ]

    if m.get("project_overview"):
        lines += ["## Project Overview", m["project_overview"], ""]

    if m.get("architecture"):
        lines += ["## Relevant Architecture", m["architecture"], ""]

    if m.get("technologies"):
        lines += ["## Technologies"]
        for t in m["technologies"]:
            lines.append(f"- {t}")
        lines.append("")

    if m.get("key_decisions"):
        lines += ["## Key Decisions to Respect"]
        for d in m["key_decisions"]:
            lines.append(f"- {d}")
        lines.append("")

    if m.get("known_issues"):
        lines += ["## Known Issues (May Be Relevant)"]
        for i in m["known_issues"]:
            lines.append(f"- ⚠️ {i}")
        lines.append("")

    if m.get("agent_instructions"):
        lines += ["## Agent Instructions"]
        for i in m["agent_instructions"]:
            lines.append(f"- {i}")
        lines.append("")

    lines += [
        "---",
        f"_Focus only on the task above. Update project memory after completing it._"
    ]

    return "\n".join(lines)


def compute_completeness(memory: dict) -> dict:
    """Score memory completeness and flag missing fields."""
    fields = {
        "project_overview": ("Project Overview", "text"),
        "requirements":     ("Requirements",     "list"),
        "architecture":     ("Architecture",     "text"),
        "technologies":     ("Technologies",     "list"),
        "current_progress": ("Current Progress", "list"),
        "key_decisions":    ("Key Decisions",    "list"),
        "pending_tasks":    ("Pending Tasks",    "list"),
        "known_issues":     ("Known Issues",     "list"),
        "agent_instructions": ("Agent Instructions", "list"),
    }

    filled = 0
    missing = []
    warnings = []

    for key, (label, kind) in fields.items():
        val = memory.get(key)
        has_value = bool(val) if kind == "text" else bool(val and len(val) > 0)
        if has_value:
            filled += 1
        else:
            missing.append(label)

    score = round((filled / len(fields)) * 100)

    if not memory.get("agent_instructions"):
        warnings.append("No agent instructions — the next agent won't know your constraints.")
    if not memory.get("pending_tasks"):
        warnings.append("No pending tasks — the next agent won't know what to work on.")
    if not memory.get("architecture"):
        warnings.append("No architecture description — the next agent may make structural mistakes.")

    freshness = "unknown"

    return {
        "score": score,
        "filled": filled,
        "total": len(fields),
        "missing": missing,
        "warnings": warnings,
        "freshness": freshness,
        "ready_for_handoff": score >= 60 and not missing[:3]
    }


@router.get("/prompt")
def get_full_prompt(project_id: str):
    project = get_project(project_id)
    record = get_memory(project_id)
    m = record["memory_data"]
    version = record["version"]

    prompt = build_full_prompt(project, m, version)
    completeness = compute_completeness(m)

    return {
        "prompt": prompt,
        "token_count": count_tokens(prompt),
        "version": version,
        "completeness": completeness
    }


@router.post("/task-prompt")
def get_task_prompt(project_id: str, data: dict):
    task = data.get("task", "").strip()
    if not task:
        raise HTTPException(status_code=400, detail="Task is required")

    project = get_project(project_id)
    record = get_memory(project_id)
    m = record["memory_data"]
    version = record["version"]

    prompt = build_task_prompt(project, m, version, task)

    return {
        "prompt": prompt,
        "token_count": count_tokens(prompt),
        "task": task,
        "version": version
    }


@router.get("/completeness")
def get_completeness(project_id: str):
    record = get_memory(project_id)
    return compute_completeness(record["memory_data"])